use std::path::Path;

use pulldown_cmark::{html, Parser};
use syntect::highlighting::ThemeSet;
use syntect::html::highlighted_html_for_string;
use syntect::parsing::SyntaxSet;

use crate::FileKind;

/// HTML theme CSS (base16-ocean.dark from syntect, inline-styled already).
/// We only need the wrapper CSS for the overall page.
const HTML_TEMPLATE: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
*, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{
    background: #2b303b;
    color: #c0c5ce;
    font-family: "JetBrains Mono", "Cascadia Code", "Fira Code", "Consolas", monospace;
    font-size: 13px;
    line-height: 1.5;
    padding: 0;
    margin: 0;
    min-height: 100vh;
}}
.header {{
    position: sticky;
    top: 0;
    z-index: 10;
    background: #1f2229;
    border-bottom: 1px solid #37404a;
    padding: 10px 20px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}}
.header .title {{
    font-size: 14px;
    font-weight: bold;
    color: #96b5b4;
}}
.header .meta {{
    font-size: 11px;
    color: #65737e;
}}
pre {{
    padding: 16px 20px;
    overflow-x: auto;
    tab-size: 4;
    -moz-tab-size: 4;
}}
pre code {{
    counter-reset: line;
}}
pre code .line {{
    display: block;
    line-height: 1.5;
}}
pre code .line::before {{
    counter-increment: line;
    content: counter(line);
    display: inline-block;
    width: 3em;
    padding-right: 1.5em;
    text-align: right;
    color: #4f5b66;
    user-select: none;
}}
.markdown-body {{
    padding: 20px;
    max-width: 900px;
    margin: 0 auto;
}}
.markdown-body h1, .markdown-body h2, .markdown-body h3, .markdown-body h4 {{
    color: #8fa1b3;
    margin-top: 1.5em;
    margin-bottom: 0.5em;
}}
.markdown-body h1 {{ font-size: 1.6em; border-bottom: 1px solid #37404a; padding-bottom: 0.3em; }}
.markdown-body h2 {{ font-size: 1.3em; border-bottom: 1px solid #37404a; padding-bottom: 0.2em; }}
.markdown-body h3 {{ font-size: 1.1em; }}
.markdown-body p, .markdown-body li {{ line-height: 1.7; }}
.markdown-body a {{ color: #8fa1b3; text-decoration: underline; }}
.markdown-body a:hover {{ color: #c0c5ce; }}
.markdown-body code {{
    background: #1f2229;
    border-radius: 3px;
    padding: 2px 6px;
    font-family: "JetBrains Mono", "Fira Code", "Consolas", monospace;
    font-size: 0.9em;
    color: #bf616a;
}}
.markdown-body pre code {{
    background: none;
    padding: 0;
    color: inherit;
    font-size: inherit;
}}
.markdown-body pre {{
    background: #1f2229;
    border-radius: 4px;
    padding: 12px 16px;
    overflow-x: auto;
}}
.markdown-body blockquote {{
    border-left: 3px solid #4f5b66;
    color: #65737e;
    padding-left: 12px;
    margin: 1em 0;
}}
.markdown-body table {{
    border-collapse: collapse;
    width: 100%;
    margin: 1em 0;
}}
.markdown-body th, .markdown-body td {{
    border: 1px solid #37404a;
    padding: 6px 10px;
    text-align: left;
}}
.markdown-body th {{
    background: #1f2229;
    color: #8fa1b3;
}}
.markdown-body img {{
    max-width: 100%;
    border-radius: 4px;
}}
.markdown-body hr {{
    border: none;
    border-top: 1px solid #37404a;
    margin: 2em 0;
}}
.footer {{
    text-align: center;
    padding: 20px;
    color: #4f5b66;
    font-size: 11px;
    border-top: 1px solid #37404a;
    margin-top: 2em;
}}
.plain-body {{
    padding: 16px 20px;
    white-space: pre-wrap;
    word-wrap: break-word;
    line-height: 1.6;
}}
</style>
</head>
<body>
<div class="header">
    <span class="title">{title}</span>
    <span class="meta">{meta}</span>
</div>
{body}
<div class="footer">Generated by <a href="https://github.com/ccat" style="color:#65737e;">ccat</a> &mdash; {footer_text}</div>
</body>
</html>"#;

/// Wrap syntect's fragment HTML (inline-styled spans inside a `<pre>`) into
/// our full page template with line numbers.
fn source_html_fragment(html_fragment: &str) -> String {
    // syntect returns `<pre style="...">\n<span ...>...</span>\n</pre>`
    // We need to break it into lines for the counter-based line numbers

    // Extract content between <pre ...> and </pre>
    let inner = html_fragment
        .trim()
        .strip_prefix("<pre ")
        .and_then(|s| {
            let end_tag = s.find('>')?;
            Some(&s[end_tag + 1..])
        })
        .and_then(|s| s.strip_suffix("</pre>"))
        .unwrap_or(html_fragment);

    // Wrap each line in a .line span
    let mut result = String::from("<pre><code>");
    // Split by newlines, but keep the spans intact
    for line in inner.lines() {
        result.push_str("<span class=\"line\">");
        result.push_str(line);
        result.push_str("</span>\n");
    }
    result.push_str("</code></pre>");
    result
}

/// Render a file as a standalone HTML page.
pub fn cat_file_html(data: &[u8], kind: FileKind, path: &Path) -> String {
    let filename = path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("untitled");
    let now = chrono_now();

    match kind {
        FileKind::SourceCode => {
            let html_body = source_code_html(data, path);
            HTML_TEMPLATE
                .replace("{title}", &html_escape(filename))
                .replace(
                    "{meta}",
                    &html_escape(&format!("{} · source code", filename)),
                )
                .replace("{body}", &html_body)
                .replace("{footer_text}", &html_escape(&now))
        }
        FileKind::Markdown => {
            let html_body = markdown_html(data);
            HTML_TEMPLATE
                .replace("{title}", &html_escape(filename))
                .replace("{meta}", &format!("{} · markdown", html_escape(filename)))
                .replace(
                    "{body}",
                    &format!("<div class=\"markdown-body\">\n{html_body}\n</div>"),
                )
                .replace("{footer_text}", &html_escape(&now))
        }
        FileKind::Json | FileKind::Yaml | FileKind::Toml | FileKind::Log | FileKind::Csv => {
            // Treat structured text as source code for syntax highlighting
            let html_body = source_code_html(data, path);
            HTML_TEMPLATE
                .replace("{title}", &html_escape(filename))
                .replace("{meta}", &html_escape(&format!("{} · data", filename)))
                .replace("{body}", &html_body)
                .replace("{footer_text}", &html_escape(&now))
        }
        _ => {
            // Plain text fallback
            let content = String::from_utf8_lossy(data);
            let escaped = html_escape(&content);
            let body = format!("<div class=\"plain-body\">{}</div>", escaped);
            HTML_TEMPLATE
                .replace("{title}", &html_escape(filename))
                .replace("{meta}", &html_escape(&format!("{} · text", filename)))
                .replace("{body}", &body)
                .replace("{footer_text}", &html_escape(&now))
        }
    }
}

fn source_code_html(data: &[u8], path: &Path) -> String {
    let ss = SyntaxSet::load_defaults_newlines();
    let ts = ThemeSet::load_defaults();
    let theme = &ts.themes["base16-ocean.dark"];

    let s = String::from_utf8_lossy(data);
    let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
    let syntax = ss
        .find_syntax_by_extension(ext)
        .unwrap_or_else(|| ss.find_syntax_plain_text());

    match highlighted_html_for_string(&s, &ss, syntax, theme) {
        Ok(fragment) => source_html_fragment(&fragment),
        Err(_) => {
            // Fallback to plain pre
            let escaped = html_escape(&s);
            format!(
                "<pre><code><span class=\"line\">{}</span></code></pre>",
                escaped
            )
        }
    }
}

fn markdown_html(data: &[u8]) -> String {
    let s = String::from_utf8_lossy(data);
    let parser = Parser::new(&s);
    let mut html_output = String::new();
    html::push_html(&mut html_output, parser);
    html_output
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn chrono_now() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let dur = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    let secs = dur.as_secs();
    // Simple UTC formatting without chrono dep
    let days = secs / 86400;
    let time_secs = secs % 86400;
    let hours = time_secs / 3600;
    let minutes = (time_secs % 3600) / 60;
    let seconds = time_secs % 60;

    // Calculate year/month/day from days since epoch
    let (year, month, day) = days_to_date(days as i64);
    format!(
        "{:04}-{:02}-{:02} {:02}:{:02}:{:02} UTC",
        year, month, day, hours, minutes, seconds
    )
}

fn days_to_date(days: i64) -> (i64, u32, u32) {
    // Howard Hinnant's civil-from-days algorithm
    // http://howardhinnant.github.io/date_algorithms.html
    let z = days + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = z - era * 146097; // [0, 146096]
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1; // [1, 31]
    let m = if mp < 10 { mp + 3 } else { mp - 9 }; // [1, 12]
    let y = y + if m <= 2 { 1 } else { 0 };
    (y, m as u32, d as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_html_escape() {
        assert_eq!(html_escape("hello"), "hello");
        assert_eq!(html_escape("<tag>"), "&lt;tag&gt;");
        assert_eq!(html_escape("a & b"), "a &amp; b");
        assert_eq!(html_escape("\"'"), "&quot;&#39;");
    }

    #[test]
    fn test_source_html_rust() {
        let code = b"fn main() {\n    let x = 42;\n}\n";
        let path = Path::new("test.rs");
        let html = cat_file_html(code, FileKind::SourceCode, path);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("test.rs"));
        assert!(html.contains("<span class=\"line\">"));
        assert!(html.contains("</html>"));
    }

    #[test]
    fn test_markdown_html() {
        let md = b"# Hello\n\nThis is **bold** text.\n";
        let path = Path::new("test.md");
        let html = cat_file_html(md, FileKind::Markdown, path);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<h1>"));
        assert!(html.contains("<strong>"));
    }

    #[test]
    fn test_plain_text_html() {
        let text = b"just some\ntext content\n";
        let path = Path::new("file.txt");
        let html = cat_file_html(text, FileKind::PlainText, path);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("plain-body"));
    }

    #[test]
    fn test_days_to_date() {
        // Unix epoch
        let (y, m, d) = days_to_date(0);
        assert_eq!(y, 1970);
        assert_eq!(m, 1);
        assert_eq!(d, 1);

        // Known date
        let (y2, m2, _d2) = days_to_date(20000);
        assert_eq!(y2, 2024);
        assert_eq!(m2, 10);
    }

    #[test]
    fn test_chrono_now_format() {
        let s = chrono_now();
        assert!(s.len() > 15);
        assert!(s.contains("UTC"));
        assert!(s.contains('-'));
    }
}
